Only fails at end of job

diff --git a/.github/workflows/Pylint.yaml b/.github/workflows/Pylint.yaml
--- a/.github/workflows/Pylint.yaml
+++ b/.github/workflows/Pylint.yaml
@@ -28,11 +28,14 @@ jobs:
       run: |
               for file in $(git ls-files '*.py')
               do
-                pylint --disable=import-error,R,wildcard-import,unused-wildcard-import,attribute-defined-outside-init --max-line-length=115 --fail-under=9.0 $file  
-
+                pylint --disable=import-error,R,wildcard-import,unused-wildcard-import,attribute-defined-outside-init --max-line-length=115 --fail-under=9.0 $file || lint_failed="failed"
+              done
+              if [ "$lint_failed" = "failed" ]
+              then
+                exit 1
+              fi
       continue-on-error: true
     - name: Checks for failure
       id: Fail
-      if: steps.lint.outcome == 'failure'
+      if: steps.lint.outcome == 'failed'
       run: exit 1
-
