additional linter logging

diff --git a/.github/workflows/Pylint.yaml b/.github/workflows/Pylint.yaml
--- a/.github/workflows/Pylint.yaml
+++ b/.github/workflows/Pylint.yaml
@@ -29,14 +29,16 @@ jobs:
     - name: Analysing the code with pylint and handling exit code
       id: lint
       run: |
+              lint_failed=""
               for file in $(git ls-files '*.py')
               do
-              
-                pylint --disable=import-error,R,wildcard-import,unused-wildcard-import,attribute-defined-outside-init --max-line-length=115 --fail-under=9.0 $file || lint_failed="failed"
-                
+                  echo "Linting $file..."
+                  pylint --disable=import-error,R,wildcard-import,unused-wildcard-import,attribute-defined-outside-init --max-line-length=115 --fail-under=9.0 $file || lint_failed="failed"
+                  if [ "$lint_failed" = "failed" ]; then
+                      echo "Linting failed for $file"
+                  fi
               done
               if [ "$lint_failed" = "failed" ]
               then
-                exit 1
+                  exit 1
               fi
-
